# Generated by Django 5.0.2 on 2024-03-01 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateField(default=datetime.date(2024, 3, 1))),
            ],
        ),
    ]
